credentials:
  usernames:
    kartik_rana:
      email: kartik711111@gmail.com
      name: "Kartik Rana"
      password: "$2b$12$PpIYN7hAlwOsbSBfY2zeleAGjqbeK1FtJMycsa6/f4SWOBuDNOhIu"
    admin:
      email: admin@casetracker.com
      name: "Admin User"
      password: "$2b$12$85pBEf0RvZZPXCRlHkj4/OMbIw6atVuszUMtvDgAerIpORyjWjiee"
    jane_smith:
      email: jane@casetracker.com
      name: "Jane Smith"
      password: "$2b$12$1d2v59cWdZb/L3EKgKzsDeBKdjsyRBOoKZ8BHHlndtrIq5AIPb0ky"
    john_doe:
      email: john@casetracker.com
      name: "John Doe"
      password: "$2b$12$SlEGaL8SOI9gYwqB.3kvAuI9GRn.NJ5Efr2CvN2SPEhOW3waVmgRK"
    testuser:
      email: test@example.com
      name: "Test User"
      password: "$2b$12$0QTml/klVaIpkpVrE/xy9.Ur9tVc/HFAbTX7WqM/J0OpbklhS0Tza"

cookie:
  name: "casetracker_auth"
  key: "casetracker_signature_key_2024_secure_random_string"
  expiry_days: 30

preauthorized:
  emails:
    - "kartik711111@gmail.com"
    - "admin@casetracker.com"
    - "jane@casetracker.com"
    - "john@casetracker.com"
    - "test@example.com"